version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - ${BASE}/data:/usr/share/elasticsearch/data
      - ${BASE}/logs:/usr/share/elasticsearch/logs
    environment:
      - "cluster.name=globular"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    volumes:
      - ${BASE}/logs:/var/log/kibana
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
